# Generated by Django 6.0.6 on 2026-07-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackerlog',
            name='attacker_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
