# Generated by Django 6.0.6 on 2026-07-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_attackerlog_attacker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackerlog',
            name='cyber_dna',
            field=models.CharField(default='GEN-000-UNK', max_length=100),
        ),
    ]
