# Generated by Django 6.0.6 on 2026-07-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_attackerlog_cyber_dna'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
